/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'dtw20' at '17/12/16 10:39 PM' with Gradle 2.14.1
 *
 * @author dtw20, @date 17/12/16 10:39 PM
 */
public class Library {
	public boolean someLibraryMethod() {
		System.out.println("Hello world1");
		
		return true;
	}
}
